### PR TITLE
PLAT-4525 Add github actions validations for terraform

### PR DESCRIPTION
**Pull request by miguelhar**
Adding terraform merge validations
[PLAT-4525](https://dominodatalab.atlassian.net/browse/PLAT-4525)

### CODE REVIEW

**Comment by ddl-dclegg** [comment]
This looks pretty good @miguelhar! Should this PR be considered the replacement for #84, or in addition to it?

**Comment by miguelhar** [comment]
> This looks pretty good @miguelhar! Should this PR be considered the replacement for #84, or in addition to it?

A replacement, 84 was opened from a fork and .

**Review by fraenkel — APPROVED** [review]
why not just run all the hooks rather than specific ones?

**Comment by miguelhar** [comment]
> why not just run all the hooks rather than specific ones?

Running the checks in parallel. there specific installs for each, its better to isolate them into their own action. It also looks better.

**Pull request merged**
